---
title: "chemical_fp"
author: "Fang Liu"
date: "1/20/2022"
output: html_document
---

Load the required packages
```{r}
library(tidyverse)
library(readxl)
```


```{r}
#load original data file: 7,170 compounds
filtered_tox21 = read.delim("./data/clusters.txt") 

#load the aggregated file with CAS and SMILES: 19,334 rows
aggregated_tox21 = read_xlsx("./data/tox21_aggregated.xlsx") %>% 
  janitor::clean_names() %>% 
  rename(ncgc = sample_id) %>% 
  select(cas, smiles)

#extract the unique CAS and smiles
aggregated_tox21_2 <- aggregated_tox21[!duplicated(aggregated_tox21[, c("cas", "smiles")]), ]
```

```{r}
#THIS IS A TEST!!!
aggregated_tox21 = read_xlsx("./data/tox21_aggregated.xlsx")
write.table(aggregated_tox21, file = "TEST.txt", sep = "\t") 
result_test = read.delim("TEST.txt") 
```


NOTE: descriptors_output.csv is Chunxu's fingerprint file...
fingerprint_tox21 = read.csv("./data/descriptors_output.csv") %>% 
  janitor::clean_names() %>% 
  rename(ncgc = name)


Combine data using the cas as the "key"
```{r}
data_combined = 
  left_join(filtered_tox21, aggregated_tox21_2, by = "cas") %>% 
  distinct()

#length(unique(data_combined$cas)) #7,170 unique rows
```


# Check if there are missing values
```{r}
sum(is.na(data_combined$smiles))
#NOTE: we don't have the smiles for 245 of the compounds; 7170 - 245 = 6,925

#after removing all non-complete rows, we are left with 6,925 observations... 
non_missing = data_combined %>% remove_missing()
#nrow(data_combined %>% remove_missing()) #6,925

#Find which compounds/drugs are actually missing the "SMILES" 
missing = data_combined %>% filter(is.na(smiles)) #245

#cluster_and_smiles = data_combined %>% select(cluster, smiles)
#write_csv(cluster_and_smiles,"./result/cluster_and_smiles.csv")
```




```{r}
#NOTE: this is when joining Sue's fingerprint data to get the "bit" arrays:
final_data =
  left_join(data_combined, fingerprint_tox21, by = "ncgc") %>% 
  distinct(cas, .keep_all = TRUE) %>% 
  remove_missing()
```

```{r}
smiles = final_data %>% select(smiles)
write_csv(smiles, "./result/smiles.csv")
```

#create csv with cluster and smiles
```{r}
cluster_and_smiles = final_data %>% select(cluster, smiles)
write_csv(cluster_and_smiles, "./result/cluster_and_smiles.csv")
```
